[CmdletBinding()]
param(
	[Parameter(Mandatory = $true)][string]$exe
)
$verboseArg=$null
if ($PSBoundParameters.ContainsKey('Verbose')) { $verboseArg='-v' }

# delete files to be generated by the test
Remove-Item -Path (Join-Path $PSScriptRoot "test-commands-1.obj") -ErrorAction SilentlyContinue

# run test
& $exe run (Join-Path $PSScriptRoot "test-commands-1.lua") $verboseArg -arg sizex=3 -arg hello
if ($LASTEXITCODE -ne 0) { throw }

# validate files generated
cd $PSScriptRoot

.\Compare-WavefrontObjFiles.ps1 .\test-commands-1.obj .\test-commands-1-1.obj
if ($LASTEXITCODE -ne 0) { cd -; throw }

cd -

#done
