[CmdletBinding()]
param(
	[Parameter(Mandatory = $true)][string]$exe
)
$verboseArg=$null
if ($PSBoundParameters.ContainsKey('Verbose')) { $verboseArg='-v' }

# delete files to be generated by the test
Remove-Item -Path (Join-Path $PSScriptRoot "test-obj.obj") -ErrorAction SilentlyContinue

# run test
& $exe run (Join-Path $PSScriptRoot "gen-test-obj.lua") $verboseArg
if ($LASTEXITCODE -ne 0) { throw }

# validate files generated
cd $PSScriptRoot

.\Compare-WavefrontObjFiles.ps1 .\test-obj.obj .\test-obj-1.obj
if ($LASTEXITCODE -ne 0) { cd -; throw }

.\Compare-WavefrontObjFiles.ps1 .\test-obj.obj .\test-obj-2.obj
if ($LASTEXITCODE -ne 0) { cd -; throw }

cd -

#done
